import { FontSizes } from '@/constants/Colors';
import { StyleSheet } from 'react-native';
import { Theme } from './constants';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Theme.background,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
    backgroundColor: Theme.background,
    gap: 16,
  },
  headerCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundColor: Theme.cardBg,
    borderRadius: 8,
    padding: 16,
    borderWidth: 3,
    borderColor: '#000000',
    shadowColor: '#000000',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  headerTextWrap: { flexDirection: 'column', flex: 1 },
  headerGreeting: { fontSize: FontSizes.sm, color: Theme.textMuted, marginBottom: 4, fontWeight: '500' },
  headerTitle: { fontSize: FontSizes.xl, fontWeight: '800', color: Theme.textMain, marginTop: 2 },
  headerSubtitle: { fontSize: FontSizes.xl, color: Theme.textMuted, fontWeight: '500' },
  headerAccent: { color: Theme.primaryDark, fontWeight: '800' },
  datePill: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: 'rgba(191,231,193,0.7)', borderRadius: 999,
    paddingVertical: 8, paddingHorizontal: 12, backgroundColor: 'rgba(255,255,255,0.45)', gap: 4,
  },
  demoCard: {
    flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: Theme.cardBg,
    borderRadius: 8, paddingHorizontal: 16, paddingVertical: 14, marginHorizontal: 0,
    borderWidth: 3, borderColor: '#000000',
    shadowColor: '#000000', shadowOffset: { width: 5, height: 5 }, shadowOpacity: 1, shadowRadius: 0,
    elevation: 3,
  },
  demoCopy: { flex: 1 },
  demoTitle: { fontSize: FontSizes.sm, fontWeight: '800', color: Theme.textMain },
  demoSubTitle: { marginTop: 4, fontSize: FontSizes.xs, lineHeight: 16, color: Theme.textMuted },
  demoToggle: { paddingHorizontal: 16, paddingVertical: 12, borderRadius: 16, borderWidth: 2, borderColor: '#000000', backgroundColor: Theme.white, shadowColor: '#000000', shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0 },
  demoToggleActive: { backgroundColor: Theme.primary },
  demoToggleText: { color: Theme.textMuted, fontSize: FontSizes.xs, fontWeight: '700' },
  demoToggleTextActive: { color: '#000000' },
  demoControls: { backgroundColor: Theme.cardBg, borderRadius: 18, paddingHorizontal: 18, paddingVertical: 18, marginHorizontal: 0, borderWidth: 2, borderColor: '#000000', gap: 12, shadowColor: '#000000', shadowOffset: { width: 6, height: 6 }, shadowOpacity: 1, shadowRadius: 0, elevation: 3 },
  demoInputRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  demoInput: { flex: 1, minWidth: 0, backgroundColor: Theme.white, borderWidth: 2, borderColor: '#000000', borderRadius: 16, paddingHorizontal: 14, paddingVertical: 12, color: Theme.textMain, fontSize: FontSizes.sm, fontWeight: '700', height: 50 },
  demoAction: { paddingHorizontal: 16, paddingVertical: 12, borderRadius: 16, backgroundColor: Theme.primary, borderWidth: 2, borderColor: '#000000', shadowColor: '#000000', shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0 },
  demoActionText: { color: '#000000', fontSize: FontSizes.xs, fontWeight: '800' },
  demoCategoryRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  categoryChip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 16, backgroundColor: Theme.white, borderWidth: 2, borderColor: '#000000' },
  categoryChipActive: { backgroundColor: Theme.primary },
  categoryChipText: { color: '#000000', fontSize: FontSizes.xs, fontWeight: '800' },
  categoryChipTextActive: { color: '#000000' },
  resetDemoButton: { marginLeft: 'auto', paddingHorizontal: 10, paddingVertical: 8 },
  resetDemoText: { color: Theme.textMuted, fontSize: FontSizes.xs, fontWeight: '700' },
  balanceCard: { borderRadius: 18, marginHorizontal: 0, shadowColor: '#000000', shadowOffset: { width: 6, height: 6 }, shadowOpacity: 1, shadowRadius: 0, elevation: 6, overflow: 'hidden', borderWidth: 2, borderColor: '#000000' },
  balanceBackgroundImage: { minHeight: 230, width: '100%' },
  balanceBackgroundImageStyle: { borderRadius: 15 },
  balanceFadeOverlay: { ...StyleSheet.absoluteFillObject },
  balanceContent: { flex: 1, paddingHorizontal: 22, paddingTop: 22, paddingBottom: 16 },
  balanceMainSection: { width: '100%', gap: 4 },
  balanceValueRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 4 },
  balanceDetailsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%' },
  balanceLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  balanceEye: { alignSelf: 'center' },
  balanceLabel: { color: Theme.textMain, fontSize: FontSizes.sm, fontWeight: '700' },
  balanceValue: { color: Theme.textMain, fontSize: 32, fontWeight: '800', flexShrink: 1 },
  healthBadge: { alignSelf: 'center', backgroundColor: Theme.sunlight, paddingVertical: 6, paddingHorizontal: 12, borderRadius: 12, borderWidth: 2, borderColor: '#000000' },
  healthBadgeText: { color: '#000000', fontSize: FontSizes.sm, fontWeight: '800' },
  spendInfo: { flex: 1, paddingRight: 8, minWidth: 0 },
  spendLabel: { color: Theme.textMain, fontSize: FontSizes.sm, fontWeight: '600' },
  spendValue: { color: Theme.textMain, fontSize: 24, fontWeight: '700', flexShrink: 1, marginTop: 4 },
  spendSubLabel: { color: Theme.textMain, fontSize: FontSizes.xs, marginTop: 4, fontWeight: '600' },
  circularChart: { width: 72, height: 72, alignItems: 'center', justifyContent: 'center' },
  circularText: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  circularValue: { color: Theme.white, fontSize: 16, fontWeight: '700' },
  circularLabel: { color: Theme.whiteSoft, fontSize: FontSizes.xs },
  progressTrack: { width: '100%', height: 10, borderRadius: 999, backgroundColor: 'rgba(249,255,250,0.1)', marginTop: 18, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999 },
  balanceBottomDivider: { marginTop: 18, marginBottom: 14, height: 2, width: '100%', backgroundColor: '#000000' },
  bottomRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: 18, borderWidth: 2, borderColor: '#000000', paddingHorizontal: 16, paddingVertical: 14 },
  bottomItems: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  bottomItem: { flex: 1, flexDirection: 'row', alignItems: 'center', minWidth: 0 },
  bottomIconWrap: { width: 30, height: 30, borderRadius: 999, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(249,255,250,0.78)', marginRight: 10 },
  bottomText: { flex: 1, minWidth: 0 },
  bottomItemDivider: { width: 2, height: 36, backgroundColor: 'rgba(249,255,250,0.22)', marginHorizontal: 10 },
  bottomValue: { color: '#000000', fontSize: FontSizes.sm, fontWeight: '800' },
  bottomLabel: { color: '#000000', fontSize: FontSizes.xs, marginTop: 2, fontWeight: '600' },
  insightGrid: { gap: 16 },
  plannerCard: { backgroundColor: Theme.cardBg, borderRadius: 18, padding: 18, borderWidth: 2, borderColor: '#000000', shadowColor: '#000000', shadowOffset: { width: 6, height: 6 }, shadowOpacity: 1, shadowRadius: 0, elevation: 3 },
  plannerHeroRow: { flexDirection: 'row', gap: 10, alignItems: 'stretch', marginTop: 10 },
  plannerLeft: { flex: 1.1, gap: 8 },
  plannerTypeName: { color: Theme.textMain, fontSize: FontSizes.lg, fontWeight: '900' },
  plannerIconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  plannerIconBox: { width: 38, height: 38, borderRadius: 12, backgroundColor: 'rgba(191,231,193,0.18)', borderWidth: 1, borderColor: 'rgba(191,231,193,0.35)', alignItems: 'center', justifyContent: 'center' },
  plannerImageContainer: { flex: 0.9, alignItems: 'center', justifyContent: 'center', minHeight: 110 },
  plannerImage: { width: '100%', height: 130 },
  plannerBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12, padding: 12, borderRadius: 16, borderWidth: 2, borderColor: '#000000', backgroundColor: Theme.background },
  plannerBannerIcon: { width: 28, height: 28, borderRadius: 999, alignItems: 'center', justifyContent: 'center', backgroundColor: Theme.primary },
  plannerBannerText: { flex: 1, color: Theme.textMain, fontSize: FontSizes.sm, fontWeight: '700' },
  goodAtLabel: { marginTop: 12, color: Theme.textMuted, fontSize: FontSizes.sm, fontWeight: '800' },
  traitRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 8 },
  traitPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 16, backgroundColor: Theme.background, borderWidth: 2, borderColor: '#000000' },
  traitText: { color: Theme.textMain, fontSize: FontSizes.xs, fontWeight: '800' },
  plannerBtn: { marginTop: 12, paddingVertical: 12, paddingHorizontal: 16, borderRadius: 16, backgroundColor: Theme.primary, borderWidth: 2, borderColor: '#000000', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, shadowColor: '#000000', shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0 },
  plannerBtnText: { color: '#000000', fontWeight: '900', fontSize: FontSizes.sm },
  streakCard: { backgroundColor: Theme.darkSection, borderRadius: 18, padding: 18, borderWidth: 2, borderColor: '#000000', shadowColor: '#000000', shadowOffset: { width: 6, height: 6 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4, gap: 12 },
  streakHeaderText: { color: Theme.white, fontSize: FontSizes.lg, fontWeight: '900' },
  streakRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  streakNumber: { color: Theme.white, fontSize: 42, lineHeight: 46, fontWeight: '800' },
  daysText: { color: Theme.whiteSoft, fontSize: FontSizes.lg, fontWeight: '800', paddingBottom: 4 },
  onTrackLabel: { color: Theme.whiteSoft, fontSize: FontSizes.sm, marginTop: -4, fontWeight: '600' },
  weekDotsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 },
  weekDotCol: { alignItems: 'center', gap: 4, flex: 1 },
  weekDot: { width: 22, height: 22, borderRadius: 999, borderWidth: 1, borderColor: 'rgba(249,255,250,0.24)', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(249,255,250,0.06)' },
  weekDotDone: { backgroundColor: Theme.primary, borderColor: Theme.primary },
  weekDayLbl: { color: Theme.whiteSoft, fontSize: 10, fontWeight: '700' },
  bestStreakRow: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, borderRadius: 16, borderWidth: 2, borderColor: '#000000', backgroundColor: Theme.white },
  bestStreakIconWrap: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: Theme.primaryLight },
  bestStreakTitle: { color: '#000000', fontSize: FontSizes.xs, fontWeight: '800' },
  bestStreakVal: { color: '#000000', fontSize: FontSizes.md, fontWeight: '900', marginTop: 2 },
  geckoMotivRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  geckoAvatarWrap: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: Theme.primaryLight },
  geckoMotivLine: { color: '#000000', fontSize: FontSizes.sm, fontWeight: '800', lineHeight: 18 },
  calendarSection: { marginTop: 2, paddingTop: 12, borderTopWidth: 2, borderTopColor: '#000000' },
  calendarHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  calendarTitle: { color: '#000000', fontSize: FontSizes.md, fontWeight: '900' },
  calendarMonthLabel: { color: '#000000', fontSize: FontSizes.sm, marginTop: 4, marginBottom: 8, fontWeight: '800' },
  calWeekRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  calWeekLbl: { color: '#000000', fontSize: 10, fontWeight: '800', width: 24, textAlign: 'center' },
  calGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  calDay: { width: 24, height: 24, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: Theme.background, borderWidth: 1, borderColor: '#000000' },
  calDayDone: { backgroundColor: Theme.primary, borderWidth: 2, borderColor: '#000000' },
  calDayText: { color: '#000000', fontSize: 10, fontWeight: '700' },
  calDayTextDone: { color: '#000000' },
  suggestionsBar: { backgroundColor: Theme.mintSurface, borderRadius: 18, paddingVertical: 16, paddingHorizontal: 16, borderWidth: 2, borderColor: '#000000', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, shadowColor: '#000000', shadowOffset: { width: 5, height: 5 }, shadowOpacity: 1, shadowRadius: 0, elevation: 3 },
  suggIconWrap: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: Theme.primaryLight, borderWidth: 2, borderColor: '#000000' },
  seeImpactBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, borderRadius: 16, backgroundColor: Theme.primary, borderWidth: 2, borderColor: '#000000', paddingHorizontal: 14, paddingVertical: 10, shadowColor: '#000000', shadowOffset: { width: 4, height: 4 }, shadowOpacity: 1, shadowRadius: 0 },
});