import { FontSizes } from '@/constants/Colors';
import { StyleSheet } from 'react-native';
import { Theme } from './constants';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Theme.background,
  },
  scrollContent: {
    paddingHorizontal: 10,
    paddingBottom: 10,
    backgroundColor: Theme.background,
  },
  headerCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundColor: Theme.cardBg,
    borderRadius: 24,
    padding: 10,
    borderWidth: 1,
    borderColor: Theme.glassBorder,
    shadowColor: Theme.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  headerTextWrap: { flexDirection: 'column', flex: 1 },
  headerGreeting: { fontSize: FontSizes.sm, color: Theme.textMuted, marginBottom: 4, fontWeight: '500' },
  headerTitle: { fontSize: FontSizes.xl, fontWeight: '800', color: Theme.textMain, marginTop: 2 },
  headerSubtitle: { fontSize: FontSizes.xl, color: Theme.textMuted, fontWeight: '500' },
  headerAccent: { color: Theme.primaryDark, fontWeight: '800' },
  datePill: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: 'rgba(191,231,193,0.7)', borderRadius: 999,
    paddingVertical: 8, paddingHorizontal: 12, backgroundColor: 'rgba(255,255,255,0.45)', gap: 4,
  },
  demoCard: {
    flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: Theme.cardBg,
    borderRadius: 18, paddingHorizontal: 14, paddingVertical: 12, marginHorizontal: 5, marginTop: 8,
    borderWidth: 1, borderColor: Theme.cardBorderSoft,
  },
  demoCopy: { flex: 1 },
  demoTitle: { fontSize: FontSizes.sm, fontWeight: '800', color: Theme.textMain },
  demoSubTitle: { marginTop: 4, fontSize: FontSizes.xs, lineHeight: 16, color: Theme.textMuted },
  demoToggle: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, borderWidth: 1, borderColor: Theme.cardBorder, backgroundColor: Theme.white },
  demoToggleActive: { backgroundColor: Theme.primaryDark, borderColor: Theme.primaryDark },
  demoToggleText: { color: Theme.textMuted, fontSize: FontSizes.xs, fontWeight: '700' },
  demoToggleTextActive: { color: Theme.white },
  demoControls: { backgroundColor: Theme.cardBg, borderRadius: 18, paddingHorizontal: 14, paddingVertical: 12, marginHorizontal: 5, marginTop: 8, borderWidth: 1, borderColor: Theme.cardBorderSoft, gap: 10 },
  demoInputRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  demoInput: { flex: 1, minWidth: 0, backgroundColor: Theme.white, borderWidth: 1, borderColor: Theme.cardBorder, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, color: Theme.textMain, fontSize: FontSizes.sm },
  demoAction: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, backgroundColor: Theme.primaryDark },
  demoActionText: { color: Theme.white, fontSize: FontSizes.xs, fontWeight: '700' },
  demoCategoryRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  categoryChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: 'rgba(191,231,193,0.24)', borderWidth: 1, borderColor: 'rgba(191,231,193,0.5)' },
  categoryChipActive: { backgroundColor: Theme.primary, borderColor: Theme.primary },
  categoryChipText: { color: Theme.primaryDark, fontSize: FontSizes.xs, fontWeight: '700' },
  categoryChipTextActive: { color: Theme.white },
  resetDemoButton: { marginLeft: 'auto', paddingHorizontal: 10, paddingVertical: 8 },
  resetDemoText: { color: Theme.textMuted, fontSize: FontSizes.xs, fontWeight: '700' },
  balanceCard: { borderRadius: 18, marginHorizontal: 5, shadowColor: Theme.shadow, shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.18, shadowRadius: 28, elevation: 12, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(249,255,250,0.16)' },
  balanceBackgroundImage: { minHeight: 220, width: '100%' },
  balanceBackgroundImageStyle: { borderRadius: 18 },
  balanceFadeOverlay: { ...StyleSheet.absoluteFillObject },
  balanceContent: { flex: 1, paddingHorizontal: 20, paddingTop: 25, paddingBottom: 12 },
  balanceTopRow: { flexDirection: 'row', alignItems: 'flex-start' },
  balanceTopLeft: { flex: 1, minWidth: 0 },
  balanceTopRight: { flex: 1.5, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', minWidth: 0 },
  balanceLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', alignSelf: 'stretch', width: '100%' },
  balanceEye: { marginLeft: 8, alignSelf: 'center' },
  balanceLabel: { color: Theme.textMain, fontSize: FontSizes.sm, fontWeight: '500', flex: 1, minWidth: 0, flexShrink: 1 },
  balanceValue: { color: Theme.textMain, fontSize: 30, fontWeight: '700', flexShrink: 1 },
  healthBadge: { alignSelf: 'flex-start', backgroundColor: 'rgba(91, 176, 105, 0.16)', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(249,255,250,0.18)' },
  healthBadgeText: { color: Theme.textMuted, fontSize: FontSizes.sm, fontWeight: '600' },
  spendInfo: { flex: 1, paddingRight: 8, minWidth: 0 },
  spendLabel: { color: Theme.textMain, fontSize: FontSizes.sm, fontWeight: '500' },
  spendValue: { color: Theme.textMain, fontSize: 24, fontWeight: '600', marginTop: 8, marginBottom: 4, flexShrink: 1 },
  spendSubLabel: { color: Theme.textMain, fontSize: FontSizes.xs, marginTop: 4 },
  circularChart: { width: 72, height: 72, alignItems: 'center', justifyContent: 'center' },
  circularText: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  circularValue: { color: Theme.white, fontSize: 16, fontWeight: '700' },
  circularLabel: { color: Theme.whiteSoft, fontSize: FontSizes.xs },
  progressTrack: { width: '100%', height: 8, borderRadius: 999, backgroundColor: 'rgba(249,255,250,0.1)', marginTop: 16, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999 },
  balanceBottomDivider: { marginTop: 16, marginBottom: 12, height: 1, width: '100%', backgroundColor: 'rgba(249,255,250,0.16)' },
  bottomRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: 16, borderWidth: 1, borderColor: 'rgba(249,255,250,0.12)', paddingHorizontal: 14, paddingVertical: 12 },
  bottomItems: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  bottomItem: { flex: 1, flexDirection: 'row', alignItems: 'center', minWidth: 0 },
  bottomIconWrap: { width: 28, height: 28, borderRadius: 999, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(249,255,250,0.78)', marginRight: 10 },
  bottomText: { flex: 1, minWidth: 0 },
  bottomItemDivider: { width: 1, height: 36, backgroundColor: 'rgba(249,255,250,0.22)', marginHorizontal: 10 },
  bottomValue: { color: Theme.white, fontSize: FontSizes.sm, fontWeight: '700' },
  bottomLabel: { color: Theme.whiteSoft, fontSize: FontSizes.xs, marginTop: 2 },
  insightGrid: { marginTop: 8, gap: 10 },
  plannerCard: { backgroundColor: Theme.cardBg, borderRadius: 20, padding: 14, borderWidth: 1, borderColor: Theme.cardBorderSoft, shadowColor: Theme.shadow, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.08, shadowRadius: 24, elevation: 3 },
  plannerHeroRow: { flexDirection: 'row', gap: 10, alignItems: 'stretch', marginTop: 10 },
  plannerLeft: { flex: 1.1, gap: 8 },
  plannerTypeName: { color: Theme.textMain, fontSize: FontSizes.lg, fontWeight: '800' },
  plannerIconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  plannerIconBox: { width: 38, height: 38, borderRadius: 12, backgroundColor: 'rgba(191,231,193,0.18)', borderWidth: 1, borderColor: 'rgba(191,231,193,0.35)', alignItems: 'center', justifyContent: 'center' },
  plannerImageContainer: { flex: 0.9, alignItems: 'center', justifyContent: 'center', minHeight: 110 },
  plannerImage: { width: '100%', height: 130 },
  plannerBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10, padding: 10, borderRadius: 14, backgroundColor: 'rgba(239,248,241,0.95)' },
  plannerBannerIcon: { width: 28, height: 28, borderRadius: 999, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(191,231,193,0.4)' },
  plannerBannerText: { flex: 1, color: Theme.textMain, fontSize: FontSizes.sm, fontWeight: '600' },
  goodAtLabel: { marginTop: 10, color: Theme.textMuted, fontSize: FontSizes.sm, fontWeight: '600' },
  traitRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 8 },
  traitPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 999, backgroundColor: 'rgba(239,248,241,0.9)', borderWidth: 1, borderColor: 'rgba(191,231,193,0.35)' },
  traitText: { color: Theme.textMain, fontSize: FontSizes.xs, fontWeight: '700' },
  plannerBtn: { marginTop: 12, paddingVertical: 12, paddingHorizontal: 14, borderRadius: 14, backgroundColor: 'rgba(191,231,193,0.28)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  plannerBtnText: { color: Theme.primaryDark, fontWeight: '800', fontSize: FontSizes.sm },
  streakCard: { backgroundColor: Theme.darkSection, borderRadius: 20, padding: 14, borderWidth: 1, borderColor: 'rgba(249,255,250,0.08)', shadowColor: Theme.shadow, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.12, shadowRadius: 24, elevation: 4, gap: 10 },
  streakHeaderText: { color: Theme.white, fontSize: FontSizes.lg, fontWeight: '800' },
  streakRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  streakNumber: { color: Theme.white, fontSize: 42, lineHeight: 46, fontWeight: '800' },
  daysText: { color: Theme.whiteSoft, fontSize: FontSizes.lg, fontWeight: '700', paddingBottom: 4 },
  onTrackLabel: { color: Theme.whiteSoft, fontSize: FontSizes.sm, marginTop: -4 },
  weekDotsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 },
  weekDotCol: { alignItems: 'center', gap: 4, flex: 1 },
  weekDot: { width: 22, height: 22, borderRadius: 999, borderWidth: 1, borderColor: 'rgba(249,255,250,0.24)', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(249,255,250,0.06)' },
  weekDotDone: { backgroundColor: Theme.primary, borderColor: Theme.primary },
  weekDayLbl: { color: Theme.whiteSoft, fontSize: 10, fontWeight: '700' },
  bestStreakRow: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 10, borderRadius: 16, backgroundColor: 'rgba(249,255,250,0.06)' },
  bestStreakIconWrap: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(191,231,193,0.18)' },
  bestStreakTitle: { color: Theme.whiteSoft, fontSize: FontSizes.xs, fontWeight: '700' },
  bestStreakVal: { color: Theme.white, fontSize: FontSizes.md, fontWeight: '800', marginTop: 2 },
  geckoMotivRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  geckoAvatarWrap: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(191,231,193,0.18)' },
  geckoMotivLine: { color: Theme.white, fontSize: FontSizes.sm, fontWeight: '700', lineHeight: 18 },
  calendarSection: { marginTop: 2, paddingTop: 10, borderTopWidth: 1, borderTopColor: 'rgba(249,255,250,0.1)' },
  calendarHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  calendarTitle: { color: Theme.white, fontSize: FontSizes.md, fontWeight: '800' },
  calendarMonthLabel: { color: Theme.whiteSoft, fontSize: FontSizes.sm, marginTop: 4, marginBottom: 8 },
  calWeekRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  calWeekLbl: { color: Theme.whiteSoft, fontSize: 10, fontWeight: '700', width: 24, textAlign: 'center' },
  calGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  calDay: { width: 24, height: 24, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(249,255,250,0.06)' },
  calDayDone: { backgroundColor: Theme.primary },
  calDayText: { color: Theme.whiteSoft, fontSize: 10, fontWeight: '700' },
  calDayTextDone: { color: Theme.white },
  suggestionsBar: { backgroundColor: '#aadcb6', borderRadius: 20, marginTop: 10, paddingVertical: 12, paddingRight: 12, paddingLeft: 10, borderWidth: 1, borderColor: 'rgba(249,255,250,0.08)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, shadowColor: Theme.shadow, shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.12, shadowRadius: 20, elevation: 4 },
  suggIconWrap: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(191,231,193,0.18)' },
  seeImpactBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 14, backgroundColor: Theme.primaryDark, paddingHorizontal: 8, paddingVertical: 4 },
});