import { StyleSheet } from 'react-native';

import {
    AMOUNT_DARK,
    BORDER,
    CARD_BG,
    FONTS as F,
    GREEN,
    PAGE_BG,
    TEXT_HELPER,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
} from './constants';

export const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: PAGE_BG },
  container: { paddingHorizontal: 16, paddingTop: 4, paddingBottom: 32, gap: 20 },

  header: { marginBottom: 2 },
  heading: { fontSize: F.lg, fontWeight: '900', color: TEXT_PRIMARY },
  subHeading: { marginTop: 2, fontSize: F.sm, fontWeight: '700', color: TEXT_SECONDARY },

  heroCard: {
    backgroundColor: '#FFE600',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 0,
    minHeight: 120,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#000000',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  heroImageWrap: {
    width: 104,
    alignSelf: 'stretch',
    marginRight: 10,
    marginLeft: -2,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  heroImage: { width: 104, height: 128, marginTop: -6 },
  heroBody: { flex: 1, paddingVertical: 14 },
  heroTitle: { color: TEXT_PRIMARY, fontSize: F.md, fontWeight: '900', marginBottom: 6 },
  heroText: { color: '#000000', fontSize: F.base, lineHeight: 18, fontWeight: '600' },
  streakBox: { alignItems: 'center', marginLeft: 10, paddingVertical: 14 },
  fireBadge: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
    borderWidth: 2,
    borderColor: '#000000',
  },
  streakTitle: { color: TEXT_PRIMARY, fontWeight: '900', fontSize: F.base },
  streakSub: { color: TEXT_SECONDARY, fontSize: F.xs, marginTop: 3, fontWeight: '800' },

  card: {
    backgroundColor: CARD_BG,
    borderRadius: 18,
    padding: 18,
    borderWidth: 2,
    borderColor: BORDER,
    shadowColor: '#000000',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  sectionLabel: {
    fontSize: F.xs,
    fontWeight: '900',
    color: '#000000',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 10,
  },

  insightPill: {
    marginTop: 12,
    backgroundColor: '#C3FFD8',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 2,
    borderColor: '#000000',
    shadowColor: '#000000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  insightPillLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  insightPillTitle: { fontWeight: '900', color: TEXT_PRIMARY, fontSize: F.base },
  insightPillSub: { color: '#000000', fontSize: F.xs, marginTop: 2, fontWeight: '700' },
  seeImpactBtn: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  seeImpactText: { fontSize: F.xs, color: '#000000', fontWeight: '900' },

  snapshotHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  snapshotTitleRow: { gap: 2 },
  dateTag: { fontSize: F.xs, color: '#000000', fontWeight: '700' },
  thisWeekBtn: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  thisWeekText: { fontSize: F.sm, color: '#000000', fontWeight: '900' },

  snapshotBody: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
  circleWrap: { justifyContent: 'center', alignItems: 'center' },
  circleOuter: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: '#000000',
    backgroundColor: '#00FF66',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  circleText: { fontSize: F.xl, fontWeight: '900', color: '#000000' },

  snapAmount: { fontSize: F.xl, fontWeight: '900', color: AMOUNT_DARK },
  snapOf: { fontSize: F.md, fontWeight: '700', color: '#333333' },
  snapSub: { color: '#333333', fontSize: F.sm, marginTop: 2, fontWeight: '700' },
  snapBarBg: {
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#000000',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    marginTop: 10,
  },
  snapBarFill: { height: '100%', backgroundColor: GREEN },

  /* Dummy controls */
  dummyBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#000000',
    backgroundColor: '#ffffff',
    shadowColor: '#000000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  dummyBtnActive: { backgroundColor: GREEN },
  dummyBtnText: { color: TEXT_PRIMARY, fontWeight: '900' },
  dummyControls: { marginBottom: 8 },
  input: {
    minWidth: 95,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#000000',
    fontWeight: '700',
    height: 48,
  },
  addBtn: {
    backgroundColor: GREEN,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  clearBtn: {
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 16,
    backgroundColor: '#ffffff',
    shadowColor: '#000000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },

  statsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statCol: { flex: 1, alignItems: 'center' },
  statDivider: { width: 2, height: 36, backgroundColor: '#000000' },
  statNum: { fontSize: F.xl, fontWeight: '900', color: AMOUNT_DARK },
  statLbl: { fontSize: F.xs, color: '#000000', textAlign: 'center', marginTop: 4, lineHeight: 14, fontWeight: '700' },

  twoColRow: { gap: 16 },
  catCard: { flex: 1, paddingBottom: 10 },
  catHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  thisMonthTag: { fontSize: F.xs, color: '#000000', fontWeight: '900' },

  catItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  catIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  catNameRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  catName: { fontSize: F.base, fontWeight: '800', color: TEXT_PRIMARY, flex: 1 },
  catAmt: { fontSize: F.base, fontWeight: '900', color: AMOUNT_DARK, marginRight: 4 },
  catPct: { fontSize: F.xs, fontWeight: '800', minWidth: 28, textAlign: 'right' },
  catBarBg: {
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#000000',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    marginTop: 6,
  },
  catBarFill: { height: '100%' },
  viewAllBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 4, gap: 2 },
  viewAllText: { fontSize: F.sm, color: '#000000', fontWeight: '900' },

  impactCard: {
    backgroundColor: CARD_BG,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: BORDER,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  impactCardLayout: {
    flexDirection: 'row', minHeight: 220, padding: 0, alignItems: 'stretch',
  },
  visualSection: {
    width: '60%',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    alignSelf: 'stretch',
    backgroundColor: '#FFF8E7',
    borderRightWidth: 2,
    borderColor: '#000000',
  },
  treeImage: { width: '108%', height: '108%', position: 'absolute', left: -6, top: -4 },
  fadeOverlay: { position: 'absolute', right: 0, top: 0, bottom: 0, width: '92%' },
  treeSeam: { position: 'absolute', right: -6, top: 0, bottom: 0, width: 12, backgroundColor: 'rgba(255,255,255,0.88)' },
  particlesContainer: { position: 'absolute', right: 0, top: 0, bottom: 0, width: '70%', overflow: 'hidden', opacity: 0.85 },
  particle: { position: 'absolute', borderRadius: 999, backgroundColor: 'rgba(181,219,255,0.86)' },

  impactTextContainer: {
    flex: 1, paddingVertical: 18, paddingRight: 18, paddingLeft: 20,
    justifyContent: 'center', alignItems: 'flex-start', marginLeft: -8,
  },
  impactLabel: { fontSize: 11, letterSpacing: 1.8, fontWeight: '900', color: TEXT_HELPER, textTransform: 'uppercase' },
  impactAmountBlock: { marginTop: 8 },
  impactAmt: { fontSize: 30, fontWeight: '900', color: AMOUNT_DARK },
  impactSub: { fontSize: 12, color: '#333333', marginTop: 4, fontWeight: '700' },
  impactGrowBlock: { marginTop: 12 },
  impactGrowText: { fontSize: 14, fontWeight: '700', color: TEXT_SECONDARY },

  guidanceCard: {
    backgroundColor: CARD_BG,
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 0,
    minHeight: 96,
    flexDirection: 'row',
    alignItems: 'stretch',
    borderWidth: 2,
    borderColor: BORDER,
    gap: 12,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  guidanceImgWrap: { width: 78, marginRight: 8, marginLeft: -2, justifyContent: 'flex-end', alignItems: 'center' },
  guidanceImg: { width: 78, height: 104, marginTop: -6 },
  guidanceContent: { flex: 1, justifyContent: 'center', paddingVertical: 14 },
  guidanceLabel: { fontSize: F.xs, fontWeight: '900', color: TEXT_HELPER, letterSpacing: 0.5, marginBottom: 4 },
  guidanceMain: { fontSize: F.md, fontWeight: '900', color: TEXT_PRIMARY },
  guidanceSub: { fontSize: F.xs, color: '#333333', marginTop: 4, lineHeight: 16, fontWeight: '700' },

  rewardCard: {
    borderRadius: 18,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#000000',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  rewardLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  rewardIconWrap: { width: 48, height: 48, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.22)', justifyContent: 'center', alignItems: 'center' },
  rewardTitle: { color: TEXT_PRIMARY, fontWeight: '900', fontSize: F.base },
  rewardSub: { color: TEXT_SECONDARY, fontSize: F.xs, marginTop: 3, fontWeight: '700' },
  rewardBarBg: { height: 7, borderRadius: 999, backgroundColor: 'rgba(176,198,219,0.28)', marginTop: 8, width: 130 },
  rewardBarFill: { height: '100%', width: '22%', backgroundColor: GREEN, borderRadius: 999 },
  rewardBarLabels: { marginTop: 4 },
  rewardBarLbl: { fontSize: F.xs, color: TEXT_SECONDARY },
  rewardBadge: { width: 72, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.22)', borderRadius: 14, padding: 10, marginLeft: 10 },
  rewardBadgeLbl: { color: TEXT_PRIMARY, fontWeight: '900', fontSize: F.xs, marginTop: 4, textAlign: 'center' },
  rewardBadgeSub: { color: TEXT_SECONDARY, fontSize: F.xs, textAlign: 'center' },

  tipCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#000000',
    gap: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  tipTitle: { fontWeight: '900', color: TEXT_PRIMARY, fontSize: F.base },
  tipText: { fontSize: F.xs, color: '#333333', marginTop: 2, lineHeight: 16, fontWeight: '700' },
});