import { StyleSheet } from 'react-native';
import { fontFamily, layout, palette, radius, shadows, spacing } from '@/constants/design';
import { AMOUNT_DARK, CARD_BG, GREEN, PAGE_BG, TEXT_HELPER, TEXT_PRIMARY, TEXT_SECONDARY } from './constants';

const NAV_CLEARANCE = layout.navBarHeight + layout.navBarBottomInset + 28;

export const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: PAGE_BG },
  container: { paddingHorizontal: layout.gutter, paddingTop: 4, paddingBottom: NAV_CLEARANCE, gap: spacing.lg },

  header: { marginBottom: 2 },
  heading: { fontSize: 28, fontFamily: fontFamily.bold, color: TEXT_PRIMARY, letterSpacing: -0.3 },
  subHeading: { marginTop: 2, fontSize: 13, fontFamily: fontFamily.medium, color: TEXT_SECONDARY },

  heroCard: {
    backgroundColor: palette.primaryLight,
    borderRadius: radius.xxl,
    paddingHorizontal: 18,
    paddingVertical: 0,
    minHeight: 128,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    ...shadows.sm,
  },
  heroImageWrap: {
    width: 104,
    alignSelf: 'stretch',
    marginRight: 10,
    marginLeft: -2,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  heroImage: { width: 104, height: 128, marginTop: -6 },
  heroBody: { flex: 1, paddingVertical: 16 },
  heroTitle: { color: TEXT_PRIMARY, fontSize: 16, fontFamily: fontFamily.bold, marginBottom: 6 },
  heroText: { color: palette.textSecondary, fontSize: 13, lineHeight: 19, fontFamily: fontFamily.medium },
  streakBox: { alignItems: 'center', marginLeft: 10, paddingVertical: 16 },
  fireBadge: {
    width: 46,
    height: 46,
    borderRadius: radius.md,
    backgroundColor: palette.card,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
    ...shadows.xs,
  },
  streakTitle: { color: TEXT_PRIMARY, fontFamily: fontFamily.bold, fontSize: 14 },
  streakSub: { color: palette.primaryDeep, fontSize: 11, marginTop: 3, fontFamily: fontFamily.semibold },

  card: {
    backgroundColor: CARD_BG,
    borderRadius: radius.xl,
    padding: spacing.lg,
    ...shadows.md,
  },
  sectionLabel: {
    fontSize: 11,
    fontFamily: fontFamily.bold,
    color: palette.textTertiary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
  },

  insightPill: {
    marginTop: 14,
    backgroundColor: palette.primaryLight,
    borderRadius: radius.lg,
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  insightPillLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  insightPillTitle: { fontFamily: fontFamily.bold, color: TEXT_PRIMARY, fontSize: 14 },
  insightPillSub: { color: palette.textSecondary, fontSize: 12, marginTop: 2, fontFamily: fontFamily.medium },
  seeImpactBtn: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  seeImpactText: { fontSize: 12, color: palette.primaryDeep, fontFamily: fontFamily.bold },

  snapshotHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  snapshotTitleRow: { gap: 2 },
  dateTag: { fontSize: 12, color: palette.textSecondary, fontFamily: fontFamily.medium },
  thisWeekBtn: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  thisWeekText: { fontSize: 13, color: palette.primaryDeep, fontFamily: fontFamily.bold },

  snapshotBody: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
  circleWrap: { justifyContent: 'center', alignItems: 'center' },
  circleOuter: {
    width: 60,
    height: 60,
    borderRadius: radius.pill,
    backgroundColor: palette.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleText: { fontSize: 18, fontFamily: fontFamily.bold, color: TEXT_PRIMARY },

  snapAmount: { fontSize: 22, fontFamily: fontFamily.bold, color: AMOUNT_DARK },
  snapOf: { fontSize: 14, fontFamily: fontFamily.medium, color: palette.textSecondary },
  snapSub: { color: palette.textSecondary, fontSize: 13, marginTop: 2, fontFamily: fontFamily.medium },
  snapBarBg: {
    height: 12,
    borderRadius: radius.pill,
    backgroundColor: palette.track,
    overflow: 'hidden',
    marginTop: 10,
  },
  snapBarFill: { height: '100%', backgroundColor: GREEN, borderRadius: radius.pill },

  /* Dummy controls */
  dummyBtn: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: radius.pill,
    borderWidth: 1.5,
    borderColor: palette.borderStrong,
    backgroundColor: palette.card,
  },
  dummyBtnActive: { backgroundColor: palette.primary, borderColor: palette.primary },
  dummyBtnText: { color: palette.textSecondary, fontFamily: fontFamily.semibold, fontSize: 13 },
  dummyControls: { marginBottom: 8 },
  input: {
    minWidth: 95,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radius.md,
    backgroundColor: palette.card,
    borderWidth: 1.5,
    borderColor: palette.border,
    fontFamily: fontFamily.medium,
    color: palette.textPrimary,
    height: 48,
  },
  addBtn: {
    backgroundColor: palette.primary,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    ...shadows.sm,
  },
  clearBtn: {
    justifyContent: 'center',
    paddingHorizontal: 14,
    borderWidth: 1.5,
    borderColor: palette.border,
    borderRadius: radius.md,
    backgroundColor: palette.card,
  },

  statsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statCol: { flex: 1, alignItems: 'center' },
  statDivider: { width: 1, height: 36, backgroundColor: palette.border },
  statNum: { fontSize: 20, fontFamily: fontFamily.bold, color: AMOUNT_DARK },
  statLbl: { fontSize: 11, color: palette.textSecondary, textAlign: 'center', marginTop: 4, lineHeight: 15, fontFamily: fontFamily.medium },

  twoColRow: { gap: spacing.lg },
  catCard: { flex: 1, paddingBottom: 12 },
  catHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  thisMonthTag: { fontSize: 11, color: palette.textTertiary, fontFamily: fontFamily.semibold },

  catItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  catIcon: {
    width: 38,
    height: 38,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  catNameRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  catName: { fontSize: 14, fontFamily: fontFamily.semibold, color: TEXT_PRIMARY, flex: 1 },
  catAmt: { fontSize: 14, fontFamily: fontFamily.bold, color: AMOUNT_DARK, marginRight: 6 },
  catPct: { fontSize: 12, fontFamily: fontFamily.bold, minWidth: 30, textAlign: 'right' },
  catBarBg: {
    height: 8,
    borderRadius: radius.pill,
    backgroundColor: palette.track,
    overflow: 'hidden',
    marginTop: 8,
  },
  catBarFill: { height: '100%', borderRadius: radius.pill },
  viewAllBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 6, gap: 2 },
  viewAllText: { fontSize: 13, color: palette.primaryDeep, fontFamily: fontFamily.bold },

  impactCard: {
    backgroundColor: CARD_BG,
    borderRadius: radius.xl,
    overflow: 'hidden',
    ...shadows.md,
  },
  impactCardLayout: {
    flexDirection: 'row', minHeight: 220, padding: 0, alignItems: 'stretch',
  },
  visualSection: {
    width: '58%',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    alignSelf: 'stretch',
    backgroundColor: palette.primaryLight,
  },
  treeImage: { width: '108%', height: '108%', position: 'absolute', left: -6, top: -4 },
  fadeOverlay: { position: 'absolute', right: 0, top: 0, bottom: 0, width: '92%' },
  treeSeam: { position: 'absolute', right: -6, top: 0, bottom: 0, width: 12, backgroundColor: palette.card },
  particlesContainer: { position: 'absolute', right: 0, top: 0, bottom: 0, width: '70%', overflow: 'hidden', opacity: 0.85 },
  particle: { position: 'absolute', borderRadius: 999, backgroundColor: 'rgba(124,217,87,0.7)' },

  impactTextContainer: {
    flex: 1, paddingVertical: 18, paddingRight: 18, paddingLeft: 20,
    justifyContent: 'center', alignItems: 'flex-start', marginLeft: -8,
  },
  impactLabel: { fontSize: 11, letterSpacing: 1.4, fontFamily: fontFamily.bold, color: palette.textTertiary, textTransform: 'uppercase' },
  impactAmountBlock: { marginTop: 8 },
  impactAmt: { fontSize: 28, fontFamily: fontFamily.extrabold, color: AMOUNT_DARK, letterSpacing: -0.4 },
  impactSub: { fontSize: 12, color: palette.textSecondary, marginTop: 4, fontFamily: fontFamily.medium },
  impactGrowBlock: { marginTop: 12 },
  impactGrowText: { fontSize: 14, fontFamily: fontFamily.semibold, color: TEXT_SECONDARY },

  guidanceCard: {
    backgroundColor: CARD_BG,
    borderRadius: radius.xl,
    paddingHorizontal: 18,
    paddingVertical: 0,
    minHeight: 100,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    overflow: 'hidden',
    ...shadows.md,
  },
  guidanceImgWrap: { width: 78, marginRight: 8, marginLeft: -2, justifyContent: 'flex-end', alignItems: 'center' },
  guidanceImg: { width: 78, height: 104, marginTop: -6 },
  guidanceContent: { flex: 1, justifyContent: 'center', paddingVertical: 16 },
  guidanceLabel: { fontSize: 11, fontFamily: fontFamily.bold, color: palette.textTertiary, letterSpacing: 1, marginBottom: 4 },
  guidanceMain: { fontSize: 16, fontFamily: fontFamily.bold, color: TEXT_PRIMARY },
  guidanceSub: { fontSize: 12, color: palette.textSecondary, marginTop: 4, lineHeight: 17, fontFamily: fontFamily.medium },

  rewardCard: {
    borderRadius: radius.xl,
    padding: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    ...shadows.sm,
  },
  rewardLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  rewardIconWrap: { width: 48, height: 48, borderRadius: radius.md, backgroundColor: 'rgba(255,255,255,0.55)', justifyContent: 'center', alignItems: 'center' },
  rewardTitle: { color: TEXT_PRIMARY, fontFamily: fontFamily.bold, fontSize: 14 },
  rewardSub: { color: palette.textSecondary, fontSize: 12, marginTop: 3, fontFamily: fontFamily.medium },
  rewardBarBg: { height: 7, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.6)', marginTop: 8, width: 130, overflow: 'hidden' },
  rewardBarFill: { height: '100%', width: '22%', backgroundColor: palette.primary, borderRadius: 999 },
  rewardBarLabels: { marginTop: 4 },
  rewardBarLbl: { fontSize: 11, color: palette.textSecondary, fontFamily: fontFamily.medium },
  rewardBadge: { width: 74, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.55)', borderRadius: radius.md, padding: 10, marginLeft: 10 },
  rewardBadgeLbl: { color: TEXT_PRIMARY, fontFamily: fontFamily.bold, fontSize: 11, marginTop: 4, textAlign: 'center' },
  rewardBadgeSub: { color: palette.textSecondary, fontSize: 11, textAlign: 'center', fontFamily: fontFamily.medium },

  tipCard: {
    backgroundColor: palette.card,
    borderRadius: radius.xl,
    padding: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    ...shadows.sm,
  },
  tipTitle: { fontFamily: fontFamily.bold, color: TEXT_PRIMARY, fontSize: 14 },
  tipText: { fontSize: 12, color: palette.textSecondary, marginTop: 2, lineHeight: 17, fontFamily: fontFamily.medium },
});
